hl7au/au-fhir-core-inferno

- lib/au_core_test_kit/generated/v0.3.0/au_core_test_suite.rb
- lib/au_core_test_kit/generator/templates/suite.rb.erb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/9
> Use terminology server url from the ENV

- .github/workflows/generate-tests.yaml
- Makefile
- compose.yaml
- lib/au_core_test_kit/generator.rb
- lib/au_core_test_kit/generator/ig_download.rb
- lib/au_core_test_kit/generator/suite_generator.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/33
> Add generate-tests action

- lib/au_core_test_kit/generator/special_cases.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/42
> Remove Location and PractitionerRole from special cases

- .rubocop.yml
- lib/au_core_test_kit/chained_search_test.rb
- lib/au_core_test_kit/generator.rb
- lib/au_core_test_kit/generator/chain_search_test_generator.rb
- lib/au_core_test_kit/generator/search_definition_metadata_extractor.rb
- lib/au_core_test_kit/generator/templates/chain_search.rb.erb
- lib/au_core_test_kit/search_test.rb
- lib/au_core_test_kit/search_test_properties.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/46
> WIP: Add chained search for patient:Patient.identifier

- compose.yaml
- infra/modules/au_fhir_inferno/input.tf
- lib/au_core_test_kit/generator/templates/suite.rb.erb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/35
> Change tx server from test to dev

- lib/au_core_test_kit/generator/search_test_generator.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/47
> Fix optional? method

- lib/au_core_test_kit/generator/special_cases.rb
- lib/au_core_test_kit/generator/special_identifier_search_test_generator.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/77
> Add search for Practitioner IHI-I

- lib/au_core_test_kit/chained_search_test.rb
- lib/au_core_test_kit/generator/search_test_generator.rb
- lib/au_core_test_kit/generator/templates/search.rb.erb
- lib/au_core_test_kit/search_test.rb
- lib/au_core_test_kit/special_identifier_search_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/44
> Fix search by identifier

- README.md
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/108
> Add reporting issues section to the README

- lib/au_core_test_kit/generator/validation_test_generator.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/81
> Update narrative for validation tests

- lib/au_core_test_kit/generator/assets/capability_statement_group.yaml
- lib/au_core_test_kit/helpers.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/91
> Update narrative for the Capability Statement group

- Makefile
- lib/au_core_test_kit/generator/templates/suite.rb.erb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/126
> Change the default URL

- lib/au_core_test_kit/generator/search_metadata_extractor.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/57
> Handle special case for combo searches

- lib/au_core_test_kit/generator/search_test_generator.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/120
> Add search by practitioner id for PractitionerRole test

- lib/au_core_test_kit/fhir_resource_navigation.rb
- lib/au_core_test_kit/primitive_type.rb
- lib/au_core_test_kit/search_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/138
> Fix search for the extension value

- lib/au_core_test_kit/generator/search_definition_metadata_extractor.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/140
> Fix multiple date search

- lib/au_core_test_kit/custom_groups/v0.3.0-ballot/custom_validation_group.rb
- lib/au_core_test_kit/custom_groups/v0.3.0-ballot/custom_validation_test.rb
- lib/au_core_test_kit/custom_groups/v0.4.0-preview/custom_validation_group.rb
- lib/au_core_test_kit/custom_groups/v0.4.0-preview/custom_validation_test.rb
- lib/au_core_test_kit/generator/suite_generator.rb
- lib/au_core_test_kit/generator/templates/suite.rb.erb
- lib/au_core_test_kit/helpers.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/150
> Add test group to validate any resource

- lib/au_core_test_kit/generator/group_metadata_extractor.rb
- lib/au_core_test_kit/generator/search_definition_metadata_extractor.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/155
> Add default values for diagnostic result Observation

- lib/au_core_test_kit/generator/search_test_generator.rb
- lib/au_core_test_kit/generator/templates/search.rb.erb
- lib/au_core_test_kit/search_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/163
> Add an ability to run first search for Patient as read test

- lib/au_core_test_kit/generator/templates/search.rb.erb
- lib/au_core_test_kit/search_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/164
> Add optional _count search parameter

- lib/au_core_test_kit/generator/templates/search.rb.erb
- lib/au_core_test_kit/search_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/179
> Add auto _count search parameter

- lib/au_core_test_kit/generator/assets/capability_statement_group.yaml
- lib/au_core_test_kit/helpers.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/92
> Update description for the CapabilityStatement group

- lib/au_core_test_kit/generator/search_test_generator.rb
- lib/au_core_test_kit/generator/templates/search.rb.erb
- lib/au_core_test_kit/search_test.rb
- lib/au_core_test_kit/search_test_properties.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/178
> Add an ability to activate read for first _id search automatically

- lib/au_core_test_kit/reference_resolution_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/193
> Update target_profile modification for au-specimen

- Makefile
- lib/au_core_test_kit/generator/templates/suite.rb.erb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/213
> Add footer links to the suite

- Makefile
- lib/au_core_test_kit/search_test.rb
- lib/au_core_test_kit/search_test_helpers.rb
- spec/au_core/search_test_helpers_spec.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/225
Please read comment in the issue before review the code
> Fix reference search by ID

- lib/au_core_test_kit/generator/search_definition_metadata_extractor.rb
- lib/au_core_test_kit/search_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/227
> Add all required comparators for search by date in multiple or and tests

- README.md
Updated README on reporting issues and contributions to support meeting HL7 AU FCP requirements and publishing Release 1 of the HL7 AU AU Core Inferno Testing Framework Project.
> Updated README on reporting issues and contributions

- lib/au_core_test_kit/reference_resolution_test.rb
Ref: https://github.com/hl7au/au-fhir-core-inferno/issues/251
> Fix version for the specimen profile
